apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-mirror-maker
spec:
  selector:
    matchLabels:
      app: kafka-mirror-maker
  template:
    metadata:
      labels:
        app: kafka-mirror-maker
    spec:
      containers:
      - name: kafka-mirror-maker
        image: kafka-mirror-maker
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SOURCE_CLUSTER_BOOTSTRAP_SERVERS
            value: "<source-cluster-address:port>"
          - name: SOURCE_CLUSTER_CONSUMER_GROUP
            value: "<group-id>"
          - name: NUM_STREAMS
            value: "1"
          - name: WHITELISTED_TOPICS
            value: "<pattern-matching-topics-to-be-replicated>"
          - name: SINK_CLUSTER_BOOTSTRAP_SERVERS
            value: "<sink-cluster-address:port>"
          - name: LOG_LEVEL
            value: WARN